
  export const products = [
    {
      id: 1,
      productName: 'iPhone 13 Pro',
      productImage: 'iphone13pro.jpg',
      productPrice: 60999,
      inStock: 7,
      rating: 4,
      fastDelivery: true,
      imageUrl: 'https://www.apple.com/newsroom/images/product/iphone/standard/Apple_iPhone-13-Pro_iPhone-13-Pro-Max_09142021_inline.jpg.large.jpg',
      description: 'The iPhone 13 Pro features a stunning Super Retina XDR display, powerful A15 Bionic chip, advanced camera system, and all-day battery life.'
    },
    {
      id: 2,
      productName: 'Samsung Galaxy S21 Ultra',
      productImage: 'galaxys21ultra.jpg',
      productPrice: 69999,
      inStock: 5,
      rating: 5,
      fastDelivery: false,
      imageUrl: 'https://www.itmaxmyanmar.com/storage/media/zBYDrjRGEcbGriJHVeXuDg4wLGJESqVOSwme0RNk.jpg',
      description: 'The Samsung Galaxy S21 Ultra is packed with cutting-edge technology, including a dynamic AMOLED display, powerful Exynos processor, versatile camera setup, and 5G connectivity.'
    },
    {
      id: 3,
      productName: 'Google Pixel 6 Pro',
      productImage: 'pixel6pro.jpg',
      productPrice: 58999,
      inStock: 10,
      rating: 2,
      fastDelivery: true,
      imageUrl: 'https://m.media-amazon.com/images/I/716n8eAia+L.jpg',
      description: 'The Google Pixel 6 Pro offers an incredible camera experience, seamless integration with Google services, fast performance, and a beautiful display.'
    },
    {
      id: 4,
      productName: 'OnePlus 9 Pro',
      productImage: 'oneplus9pro.jpg',
      productPrice: 48999,
      inStock: 8,
      rating: 3,
      fastDelivery: true,
      imageUrl: 'https://m.media-amazon.com/images/I/614cCf6bzyL.jpg',
      description: 'The OnePlus 9 Pro combines smooth performance, a high-refresh-rate display, powerful cameras, and Warp Charge technology for quick charging on the go.'
    },
    {
      id: 5,
      productName: 'iPhone 12',
      productImage: 'iphone12.jpg',
      productPrice: 37999,
      inStock: 6,
      rating: 1,
      fastDelivery: false,
      imageUrl: 'https://m.media-amazon.com/images/I/71E5zB1qbIL._AC_UF1000,1000_QL80_.jpg',
      description: 'The iPhone 12 offers a beautiful design, powerful performance, and an advanced dual-camera system for capturing stunning photos and videos.'
    },
    {
      id: 6,
      productName: 'Samsung Galaxy Note 20 Ultra',
      productImage: 'galaxynote20ultra.jpg',
      productPrice: 31999,
      inStock: 3,
      rating: 4,
      fastDelivery: true,
      imageUrl: 'https://www.refurbished.store/cache/images/note20u_brons_multi_600x600_BGresize_16777215-tj.png',
      description: 'The Samsung Galaxy Note 20 Ultra is a productivity powerhouse with its S Pen, large AMOLED display, and impressive performance.'
    },
    {
      id: 7,
      productName: 'Google Pixel 5',
      productImage: 'pixel5.jpg',
      productPrice: 16999,
      inStock: 9,
      rating: 1,
      fastDelivery: true,
      imageUrl: 'https://m.media-amazon.com/images/I/513w-Nev-OL.jpg',
      description: 'The Google Pixel 5 offers a pure Android experience, excellent camera capabilities, and a sleek design in a compact form factor.'
    },
    {
      id: 8,
      productName: 'OnePlus 8 Pro',
      productImage: 'oneplus8pro.jpg',
      productPrice: 27999,
      inStock: 4,
      rating: 5,
      fastDelivery: false,
      imageUrl: 'https://www.refurbished.store/cache/images/oneplus-8-pro-zwart-duo_600x600_BGresize_16777215-tj.png',
      description: 'The OnePlus 8 Pro delivers a smooth 120Hz display, fast performance, and a versatile camera system, making it an excellent flagship choice.'
    },
    {
      id: 9,
      productName: 'iPhone SE',
      productImage: 'iphonese.jpg',
      productPrice: 13999,
      inStock: 12,
      rating: 1,
      fastDelivery: true,
      imageUrl: 'https://www.apple.com/v/iphone-se/j/images/overview/colors/finish__lxiv8hx90fmu_large.jpg',
      description: 'The iPhone SE packs powerful features into a compact design, including the A13 Bionic chip, advanced camera system, and Touch ID.'
    },
    {
      id: 10,
      productName: 'Samsung Galaxy S20 FE',
      productImage: 'galaxys20fe.jpg',
      productPrice: 26999,
      inStock: 8,
      rating: 3,
      fastDelivery: false,
      imageUrl: 'https://ovantica.com/pub/media/catalog/product/cache/359e51c8e354c4e2b5af98e814f93978/s/a/samsung_s20_fe_5g_cloud_navy.jpg',
      description: 'The Samsung Galaxy S20 FE offers flagship features at a more affordable price, including a high-refresh-rate display, powerful performance, and a versatile camera setup.'
    },
    {
      id: 11,
      productName: 'Google Pixel 4a',
      productImage: 'pixel4a.jpg',
      productPrice: 13499,
      inStock: 11,
      rating: 1,
      fastDelivery: true,
      imageUrl: 'https://storage.googleapis.com/gweb-uniblog-publish-prod/images/Copy_of_Pixel_4a_Front__Back_2_Ds.width-500.format-webp.webp',
      description: 'The Google Pixel 4a delivers excellent camera performance, clean Android software, and a compact design at an affordable price.'
    },
    {
      id: 12,
      productName: 'OnePlus Nord 2',
      productImage: 'oneplusnord2.jpg',
      productPrice: 14999,
      inStock: 6,
      rating: 1,
      fastDelivery: true,
      imageUrl: 'https://oasis.opstatics.com/content/dam/oasis/page/nord-series/nord-2/gray-3-d48255.jpg.webp',
      description: 'The OnePlus Nord 2 offers a smooth AMOLED display, fast charging, and powerful performance, making it a great mid-range option.'
    },
    {
      id: 13,
      productName: 'iPhone 11',
      productImage: 'iphone11.jpg',
      productPrice: 26999,
      inStock: 9,
      rating: 4,
      fastDelivery: true,
      imageUrl: 'https://cellbuddy.in/buddy/wp-content/uploads/2022/09/11-purple-3.png',
      description: 'The iPhone 11 features a powerful dual-camera system, fast performance, and all-day battery life, delivering a great user experience.'
    },
    {
      id: 14,
      productName: 'Samsung Galaxy A52',
      productImage: 'galaxya52.jpg',
      productPrice: 13999,
      inStock: 7,
      rating: 3,
      fastDelivery: true,
      imageUrl: 'https://www.refurbished.store/cache/images/a52_multi_black_600x600_BGresize_16777215-tj.png',
      description: 'The Samsung Galaxy A52 offers a high-quality display, versatile quad-camera system, long battery life, and a sleek design at an affordable price.'
    },
    {
      id: 15,
      productName: 'Google Pixel 4 XL',
      productImage: 'pixel4xl.jpg',
      productPrice: 7999,
      inStock: 3,
      rating: 2,
      fastDelivery: false,
      imageUrl: 'https://fdn2.gsmarena.com/vv/pics/google/google-pixel-4-xl-1.jpg',
      description: 'The Google Pixel 4 XL features a smooth 90Hz display, excellent camera capabilities, and advanced AI technology for a premium smartphone experience.'
    },
    {
      id: 16,
      productName: 'OnePlus 7T',
      productImage: 'oneplus7t.jpg',
      productPrice: 25999,
      inStock: 5,
      rating: 2,
      fastDelivery: true,
      imageUrl: 'https://www.dealntech.com/wp-content/uploads/2019/09/OnePlus-7T.jpg',
      description: 'The OnePlus 7T offers a smooth 90Hz display, fast performance, and a versatile camera setup, making it a great value-for-money smartphone.'
    },
    {
      id: 17,
      productName: 'iPhone XR',
      productImage: 'iphonexr.jpg',
      productPrice: 35999,
      inStock: 4,
      rating: 1,
      fastDelivery: true,
      imageUrl: 'https://www.apple.com/newsroom/images/product/iphone/standard/iPhone_XR_red-back_09122018_carousel.jpg.large.jpg',
      description: 'The iPhone XR features a large Liquid Retina display, powerful A12 Bionic chip, and Face ID for secure authentication, offering a great iPhone experience at a more affordable price.'
    },
    {
      id: 18,
      productName: 'Samsung Galaxy Note 10+',
      productImage: 'galaxynote10plus.jpg',
      productPrice: 78999,
      inStock: 6,
      rating: 5,
      fastDelivery: false,
      imageUrl: 'https://cdn1.smartprix.com/rx-ig9vjzC5v-w420-h420/samsung-galaxy-note.jpg',
      description: 'The Samsung Galaxy Note 10+ offers a stunning display, versatile S Pen functionality, powerful performance, and a feature-rich camera system for productivity and creativity.'
    },
    {
      id: 19,
      productName: 'Google Pixel 3a',
      productImage: 'pixel3a.jpg',
      productPrice: 13499,
      inStock: 8,
      rating: 4,
      fastDelivery: true,
      imageUrl: 'https://cdn.dxomark.com/wp-content/uploads/medias/post-31251/google_pixel_3a_xl-2-1024x768.jpg',
      description: 'The Google Pixel 3a provides a great camera experience, stock Android with guaranteed updates, and solid performance at an affordable price point.'
    },
    {
      id: 20,
      productName: 'OnePlus 6T',
      productImage: 'oneplus6t.jpg',
      productPrice: 34998,
      inStock: 7,
      rating: 2,
      fastDelivery: true,
      imageUrl: 'https://m.media-amazon.com/images/I/61-FZzBlpsL._AC_UF894,1000_QL80_.jpg',
      description: 'The OnePlus 6T offers a large AMOLED display, fast performance, and a clean user interface, making it a popular choice among smartphone enthusiasts.'
    },
    {
      id: 21,
      productName: 'iPhone SE (2020)',
      productImage: 'iphonese2020.jpg',
      productPrice: 31929,
      inStock: 9,
      rating: 1,
      fastDelivery: true,
      imageUrl: 'https://www.apple.com/newsroom/images/product/iphone/standard/Apple_new-iphone-se-white_04152020_big.jpg.large.jpg',
      description: 'The iPhone SE (2020) combines the power of the A13 Bionic chip, the versatility of a single-camera system, and the familiarity of Touch ID in a compact design.'
    },
    {
      id: 22,
      productName: 'Samsung Galaxy A72',
      productImage: 'galaxya72.jpg',
      productPrice: 24599,
      inStock: 6,
      rating: 4,
      fastDelivery: false,
      imageUrl: 'https://www.itmaxmyanmar.com/storage/media/zkSssSMdjzPIdbkymmD2O3f3iMf9fAxsldvqzBt2.jpg',
      description: 'The Samsung Galaxy A72 offers a large AMOLED display, a versatile quad-camera system, long battery life, and water resistance at a competitive price.'
    },
    {
      id: 23,
      productName: 'Google Pixel 3 XL',
      productImage: 'pixel3xl.jpg',
      productPrice: 9999,
      inStock: 5,
      rating: 3,
      fastDelivery: true,
      imageUrl: 'https://www.refurbished.store/cache/images/google-pixel-3-xl-wit-multi_600x600_BGresize_16777215-tj.png',
      description: 'The Google Pixel 3 XL delivers excellent camera performance, clean software, and a crisp display, making it a reliable choice for photography enthusiasts.'
    },
    {
      id: 24,
      productName: 'OnePlus Nord',
      productImage: 'oneplusnord.jpg',
      productPrice: 24999,
      inStock: 8,
      rating: 3,
      fastDelivery: true,
      imageUrl: 'https://www.jiomart.com/images/product/original/492850717/oneplus-nord-2t-5g-256gb-12gb-ram-jade-fog-mobile-phone-digital-o492850717-p592355673-0-202208122020.jpeg?im=Resize=(420,420)',
      description: 'The OnePlus Nord offers a smooth 90Hz display, fast charging, and a capable camera system, providing a premium experience at a mid-range price.'
    },
    {
      id: 25,
      productName: 'iPhone X',
      productImage: 'iphonex.jpg',
      productPrice: 17999,
      inStock: 3,
      rating: 5,
      fastDelivery: false,
      imageUrl: 'https://www.refurbished.store/cache/images/iphone-x-zwart_600x600_BGresize_16777215-tj.png',
      description: 'The iPhone X introduced a bezel-less design, Face ID, and a stunning OLED display, pushing the boundaries of what an iPhone can do.'
    },
    {
      id: 26,
      productName: 'Samsung Galaxy A51',
      productImage: 'galaxya51.jpg',
      productPrice: 23499,
      inStock: 7,
      rating: 3,
      fastDelivery: true,
      imageUrl: 'https://fdn2.mobgsm.com/vv/pics/samsung/samsung-galaxy-a51-sm-a515-1.jpg',
      description: 'The Samsung Galaxy A51 offers a large Super AMOLED display, a versatile quad-camera setup, and long-lasting battery life at an affordable price.'
    },
    {
      id: 27,
      productName: 'Google Pixel 2 XL',
      productImage: 'pixel2xl.jpg',
      productPrice: 14999,
      inStock: 6,
      rating: 2,
      fastDelivery: true,
      imageUrl: 'https://m.media-amazon.com/images/I/51b1qR1gK0S._AC_UF894,1000_QL80_.jpg',
      description: 'The Google Pixel 2 XL offers a great camera, pure Android experience, and a vibrant OLED display, making it a reliable and feature-packed smartphone.'
    },
    {
      id: 28,
      productName: 'OnePlus 5T',
      productImage: 'oneplus5t.jpg',
      productPrice: 4999,
      inStock: 5,
      rating: 4,
      fastDelivery: true,
      imageUrl: 'https://www.addmecart.com/wp-content/uploads/2022/11/OP14.jpg',
      description: 'The OnePlus 5T boasts a sleek design, fast performance, and an impressive dual-camera system, offering flagship-level features at a more affordable price point.'
    },
    {
      id: 29,
      productName: 'iPhone 8',
      productImage: 'iphone8.jpg',
      productPrice: 15999,
      inStock: 4,
      rating: 4,
      fastDelivery: true,
      imageUrl: 'https://www.apple.com/newsroom/images/product/iphone/standard/iPhone8Plus_color_selection_inline.jpg.large.jpg',
      description: 'The iPhone 8 features a powerful A11 Bionic chip, a high-quality camera, and a familiar design, making it a reliable and capable smartphone.'
    },
    {
      id: 30,
      productName: 'Samsung Galaxy S10',
      productImage: 'galaxys10.jpg',
      productPrice: 26999,
      inStock: 3,
      rating: 5,
      fastDelivery: false,
      imageUrl: 'https://www.refurbished.store/cache/images/samsung-galaxy-s10-zwart-frontandback_600x600_BGresize_16777215-tj.png',
      description: 'The Samsung Galaxy S10 offers a stunning AMOLED display, versatile camera system, and premium build quality, providing a top-tier smartphone experience.'
    }
  ];
  